# Generated by Django 2.0.6 on 2018-06-10 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del proyecto')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('state', django_fsm.FSMField(choices=[('borrador', 'borrador'), ('revisado', 'revisado'), ('publicar', 'publicar'), ('deleted', 'deleted')], default='borrador', max_length=50, protected=True, verbose_name='Publication State')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'permissions': (('can_publish', 'Can publish project'),),
            },
        ),
    ]
