# Generated by Django 2.0.6 on 2018-06-10 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={},
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='created',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='state',
        ),
    ]
