# Generated by Django 2.0.6 on 2018-06-10 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_auto_20180610_2203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'permissions': (('can_publish', 'Can publish project'),), 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
    ]
