# Generated by Django 2.0.6 on 2018-06-10 22:06

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_auto_20180610_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='state',
            field=django_fsm.FSMField(choices=[('borrador', 'borrador'), ('revisado', 'revisado'), ('publicar', 'publicar'), ('deleted', 'deleted')], default='borrador', max_length=50, protected=True, verbose_name='Publication State'),
        ),
    ]
