# Generated by Django 2.0.6 on 2018-06-10 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0005_proyecto_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='state',
        ),
    ]
