# Generated by Django 2.0.6 on 2018-06-11 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0007_proyecto_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dificultad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre de la dificultad')),
            ],
            options={
                'verbose_name': 'Dificultad',
                'verbose_name_plural': 'Dificultades',
            },
        ),
        migrations.AddField(
            model_name='proyecto',
            name='dificultad',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dificultad', to='proyecto.Dificultad', verbose_name='Nivel de dificultad'),
        ),
    ]
