# Generated by Django 2.0.6 on 2018-06-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0009_auto_20180611_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='sector',
            field=models.ManyToManyField(blank=True, related_name='sector', to='proyecto.Sector', verbose_name='Sector de la industria'),
        ),
    ]
