# Generated by Django 2.0.6 on 2018-06-11 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0012_auto_20180611_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Influencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre de la orientación')),
            ],
            options={
                'verbose_name': 'Influencia',
                'verbose_name_plural': 'Influencias',
            },
        ),
        migrations.AddField(
            model_name='proyecto',
            name='influencia',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='influencia', to='proyecto.Influencia', verbose_name='Influencia'),
        ),
    ]
