# Generated by Django 2.0.6 on 2018-06-11 21:48

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0014_auto_20180611_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='abstract',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Abstract'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fin'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Inicio'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='justificacion',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Justificación'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='metas',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Metas'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='objetivos',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Objetivos'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='resumen',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Resumen'),
        ),
    ]
