# Generated by Django 2.0.6 on 2018-06-12 00:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0015_auto_20180611_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='hitos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
