# Generated by Django 2.0.6 on 2018-06-12 00:30

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0016_proyecto_hitos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hitos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre de la hito')),
                ('descripcion', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Inicio')),
            ],
            options={
                'verbose_name': 'Hito',
                'verbose_name_plural': 'Hitos',
            },
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='hitos',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='hitos',
            field=models.ManyToManyField(blank=True, related_name='sector', to='proyecto.Hitos', verbose_name='Hitos'),
        ),
    ]
