# Generated by Django 2.0.6 on 2018-06-12 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyecto', '0017_auto_20180612_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='principal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='principal', to=settings.AUTH_USER_MODEL, verbose_name='Investigador Principal'),
        ),
        migrations.AlterField(
            model_name='hitos',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
