# Generated by Django 2.0.6 on 2018-06-12 00:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyecto', '0018_auto_20180612_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='investigadores',
            field=models.ManyToManyField(blank=True, related_name='investigadores', to=settings.AUTH_USER_MODEL, verbose_name='Investigadores'),
        ),
    ]
