# Generated by Django 2.0.6 on 2018-06-12 01:20

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0019_proyecto_investigadores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Titulo del documento')),
                ('descripcion', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Descripción')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.RenameModel(
            old_name='Hitos',
            new_name='Hito',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='documentos',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='proyecto.Documento', verbose_name='Documentos asociados'),
        ),
    ]
