# Generated by Django 2.0.6 on 2018-06-13 01:31

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0022_auto_20180612_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='comentario',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='comentario'),
        ),
    ]
