# Generated by Django 2.0.6 on 2018-06-17 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0025_remove_proyecto_documentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyecto.Proyecto'),
        ),
    ]
