# Generated by Django 2.0.6 on 2018-06-17 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0026_documento_proyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='hitos',
        ),
        migrations.AddField(
            model_name='hito',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyecto.Proyecto'),
        ),
    ]
