# Generated by Django 2.0.6 on 2018-06-26 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0027_auto_20180617_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre de la facultad/Centro')),
            ],
            options={
                'verbose_name': 'Facultad',
                'verbose_name_plural': 'Facultades',
            },
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre de la línea de investigación')),
            ],
            options={
                'verbose_name': 'Línea',
                'verbose_name_plural': 'Líneas',
            },
        ),
        migrations.AddField(
            model_name='proyecto',
            name='linea',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linea', to='proyecto.Grupo', verbose_name='Linea'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='facultad',
            field=models.ManyToManyField(blank=True, related_name='facultad', to='proyecto.Facultad', verbose_name='Facultad'),
        ),
    ]
