# Generated by Django 2.0.6 on 2018-06-26 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0028_auto_20180626_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='grupo',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupo', to='proyecto.Grupo', verbose_name='Grupo'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='linea',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linea', to='proyecto.Grupo', verbose_name='Linea'),
        ),
    ]
