# Generated by Django 2.0.6 on 2018-06-26 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0029_auto_20180626_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='linea',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linea', to='proyecto.Linea', verbose_name='Linea'),
        ),
    ]
