# Generated by Django 2.0.6 on 2018-07-04 00:19

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0031_auto_20180701_0101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compromiso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Título')),
                ('pacto', models.DateField(blank=True, null=True, verbose_name='Fecha pactada')),
                ('entrega', models.DateField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('descripcion', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Descripción')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('finalizado', models.BooleanField(verbose_name='Finalizado')),
            ],
            options={
                'verbose_name': 'Compromiso',
                'verbose_name_plural': 'Compromisos',
            },
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='facultad',
            field=models.ManyToManyField(blank=True, related_name='proyectos', to='proyecto.Facultad', verbose_name='Facultad'),
        ),
        migrations.AddField(
            model_name='compromiso',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyecto.Proyecto'),
        ),
    ]
