# Generated by Django 2.0.6 on 2018-07-15 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0032_auto_20180704_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='hito',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='hito',
            name='icon',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Icono'),
        ),
        migrations.AlterField(
            model_name='compromiso',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compromiso', to='proyecto.Proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='grupo',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='proyecto.Grupo', verbose_name='Grupo'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='linea',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='proyecto.Linea', verbose_name='Línea'),
        ),
    ]
