# Generated by Django 2.0.6 on 2018-07-17 04:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0033_auto_20180715_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documento', to='proyecto.Proyecto'),
        ),
        migrations.AlterField(
            model_name='hito',
            name='color',
            field=models.CharField(blank=True, help_text="Agregar el valor definido en back, ejemplo: red <a target='_blank' href='https://vuecidity.wemakesites.net/style/colors'>Colores</a>.", max_length=20, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='hito',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hito',
            name='icon',
            field=models.CharField(blank=True, help_text="Agregar el nombre del icono, ejemplo: access_time <a target='_blank' href='https://materializecss.com/icons.html'>Iconos</a>.", max_length=20, null=True, verbose_name='Icono'),
        ),
        migrations.AlterField(
            model_name='hito',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hito', to='proyecto.Proyecto'),
        ),
    ]
