# Generated by Django 2.0.6 on 2018-07-01 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Foto'),
        ),
    ]
